services:
  prometheus:
    image: prometheus:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: prometheus
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.retention.size=10GB'
    networks:
      - monitoring
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  grafana:
    image: grafana:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_configs:/etc/grafana/provisioning
    networks:
      - monitoring
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  node-exporter:
    image: prom/node-exporter:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
  
  loki:
    image: grafana/loki:3.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - monitoring
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  promtail:
    image: grafana/promtail:3.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  alertmanager:
    image: prom/alertmanager:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - monitoring
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

volumes:
  prometheus_data:
    external: true
  loki_data:
    external: true
  grafana_data:
    external: true
  grafana_configs:
    external: true
  alertmanager_data:
    external: true

networks:
  monitoring:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlanid: 4096
